# Generated by Django 6.0 on 2025-12-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('coach', 'Coach'), ('player', 'Player')], max_length=11),
        ),
    ]
